spring.application.name=quick-box-server

server.port=8089

redis.host=localhost
redis.port=16379
redis.password=
redis.database=0
redis.timeout=10000
redis.pool.max-active=8
redis.pool.max-wait=-1ms
redis.pool.max-idle=8
redis.pool.min-idle=0

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Large file download support
server.tomcat.max-swallow-size=-1
server.connection-timeout=-1

