{
 "title": "QuickBox Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",id=\"G1 Eden Space\"}",
     "legendFormat": "Eden Space"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",id=\"G1 Old Gen\"}",
     "legendFormat": "Old Gen"
    },
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",id=\"G1 Survivor Space\"}",
     "legendFormat": "Survivor Space"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri!=\"\",method!=\"\"}",
     "legendFormat": "{{uri}} - {{method}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum / http_server_requests_seconds_count",
     "legendFormat": "{{uri}} - {{method}}"
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live Threads" }
   ]
  }
 ]
}